---
name: "Auto Author Assign"
on:
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
jobs:
  assign:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@9af89fc71515a100421586dfdb3dc9c984fbf411 # v2.19.4
        with:
          egress-policy: audit
      - uses: toshimaru/auto-author-assign@3e19bfc990cb1cf0589dce95e9f75289bb1e22de # v3.0.3
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
