---
name: "Test Auto Labeler"
on:
  # pull_request_target event is required for autolabeler to support all PRs including forks
  pull_request_target:
    types: [opened, reopened, edited, synchronize]
permissions: {}
jobs:
  auto_labeler:
    permissions:
      contents: read # Read the release-drafter config
      pull-requests: write # Apply labels to the pull request
    uses: ./.github/workflows/auto-labeler.yaml
    with:
      config-name: release-drafter.yaml
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
